variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

.general:
  only: [merge_requests]
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

natif-build:
  extends: .general
  stage: build
  image: registry.orfeo-toolbox.org/sdinot/otb:ubuntu-18.04-gccV0.2
  script:
    - ctest -VV -S CI/main_ci.cmake -DIMAGE_NAME:string=ubuntu-18.04-gccV0.2

shark-build:
  extends: .general
  stage: build
  image: registry.orfeo-toolbox.org/sdinot/otb:ubuntu18.04-shark3.1.4
  script:
    - ctest -VV -S CI/main_ci.cmake -DIMAGE_NAME:string=ubuntu18.04-shark3.1.4