# WARNING!
# OTB uses Git-LFS to store the (large) tests data.
# Git-LFS is mostly transparent for the user and recent versions
# are able to use Git-LFS quite efficiently.
# But Git fails to manage efficiently numerous LFS data.
# We have to use directly git-lfs wrapping commands to have an
# efficient cloning step.
# Furthermore, Git-LFS and Gitlab sufer a bug preventing usage of
# GIT_STRATEGY=fetch (https://gitlab.com/gitlab-org/gitlab-runner/issues/3318)

variables:
  BUILD_IMAGE_REGISTRY: $CI_REGISTRY/gbonnefille/otb-build-env
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: "3"
  # Disable automatic checkout to let us fetch LFS before
  GIT_CHECKOUT: "false"
  # The fetch strategy fails with LFS and GitLab
  GIT_STRATEGY: "clone"

before_script:
  # make sure LFS hooks are installed
  # - git lfs install
  # Provision efficiently the local LFS cache before checkout
  # - git lfs fetch origin $CI_COMMIT_SHA
  # Checkout the expected branch
  - git checkout $CI_COMMIT_REF_NAME

after_script:
  - python3 CI/cdash_handler.py $CI_COMMIT_SHA $CI_PROJECT_ID $CI_PROJECT_DIR $K8S_SECRET_CDASH

stages:
  - precheck
  - prepare
  - build
  - package

.general:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# WiP: Disabled to fasten CI packaging development.
# fast-build:
#   extends: .general
#   only: [merge_requests, branches]
#   stage: precheck
#   image: $CI_REGISTRY/gpasero/otb/otb-install-ubuntu-native
#   before_script:
#     - export GIT_LFS_SKIP_SMUDGE=1
#     - git checkout $CI_COMMIT_REF_NAME
#     - python3 CI/check_twin_pipelines.py
#   script:
#     - ctest -V -S CI/main_ci.cmake -DIMAGE_NAME:string=ubuntu-18.04-fast
#     - ccache -s


##
## Native builds section

.common-build:
  extends: .general
  only: [merge_requests]
  stage: build

debian-build:
  extends: .common-build
  image: $BUILD_IMAGE_REGISTRY/otb-debian-native:unstable
  script:
    - xvfb-run -a -n 1 -s "-screen 0 1024x768x24 -dpi 96" ctest -V -S CI/main_ci.cmake -DIMAGE_NAME:string=debian-unstable-gcc

ubuntu-llvm:
  extends: .common-build
  image: $BUILD_IMAGE_REGISTRY/otb-ubuntu-native:18.04
  script:
    - xvfb-run -a -n 1 -s "-screen 0 1024x768x24 -dpi 96" ctest -V -S CI/main_ci.cmake -DIMAGE_NAME:string=ubuntu-18.04-llvm
  artifacts:
    paths:
      - build/CookBook-*-html.tar.gz
      - build/Documentation/Cookbook/latex/CookBook-*.pdf
      - build/Documentation/Doxygen/OTB-Doxygen-*.tar.bz2


##
## SuperBuild XDK build section.
##

.common-prepare:
  extends: .general
  only: [merge_requests]
  stage: prepare
  before_script:
# This override the previous before_script
    - git checkout $CI_COMMIT_REF_NAME
# We are now doing the git-lfs install
# This is done after the checkout so we avoid downloading Data
# But we need it to upload the archive
    - git-lfs install
    - git config --global user.email "otbbot@orfeo-toolbox.org"
    - git config --global user.name "otbbot"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$K8S_SECRET_SSH")
# This is for debug, we are checking the owner of the ssh key
    - ssh -o StrictHostKeyChecking=no -T git@gitlab.orfeo-toolbox.org
  after_script:
    - echo "Nothing to do for after_script"
  artifacts:
    expire_in: 24 hrs
    paths:
      # This recovers logs from superbuild build
      - build/*/*/*/*.log
      - sb_branch.txt

ubuntu-superbuild-prepare:
  extends: .common-prepare
  only: [merge_requests, branches]
  image: $BUILD_IMAGE_REGISTRY/otb-ubuntu-superbuild-base:18.04
  script:
    - ctest -V -S CI/prepare_superbuild.cmake -DIMAGE_NAME:string=otb-ubuntu-superbuild-base

centos-superbuild-prepare:
  extends: .common-prepare
  image: $BUILD_IMAGE_REGISTRY/otb-centos-superbuild-base:6.6
  script:
    - ctest -V -S CI/prepare_superbuild.cmake -DIMAGE_NAME:string=otb-centos-superbuild-base

# TODO: CTT: Include osx-superbuild-prepare here.


##
## SuperBuild builds section.

.superbuild-build:
  only: [merge_requests]
  extends: .common-build
  # dependencies:
  #   - superbuild-prepare
  artifacts:
    expire_in: 1 week
    paths:
      - build/*/*/*/*.log
      # - build_packages/OTB-6.7.0-Linux64.run

ubuntu-superbuild-build:
  extends: .superbuild-build
  only: [merge_requests, branches]
  image: $BUILD_IMAGE_REGISTRY/otb-ubuntu-superbuild-base:18.04
  script:
    - xvfb-run -a -n 1 -s "-screen 0 1024x768x24 -dpi 96" ctest -VV -S CI/main_superbuild.cmake -DIMAGE_NAME:string=otb-ubuntu-superbuild-base
  dependencies:
    - ubuntu-superbuild-prepare

centos-superbuild-build:
  extends: .superbuild-build
  image: $BUILD_IMAGE_REGISTRY/otb-centos-superbuild-base:6.6
  script:
    - xvfb-run -a -n 1 -s "-screen 0 1024x768x24 -dpi 96" ctest -V -S CI/main_superbuild.cmake -DIMAGE_NAME:string=otb-centos-superbuild-base
  dependencies:
    - centos-superbuild-prepare

# TODO: CTT: Include osx-superbuild-build here.


##
## SuperBuild packaging section.

.superbuild-package:
  extends: .general
  only: [merge_requests, branches]
  stage: package
  artifacts:
    expire_in: 1 hour
    paths:
      - build/*/*/*/*.log
      - build_packages/OTB-6.7.0-Linux64.run

ubuntu-package:
  extends: .superbuild-package
  image: $BUILD_IMAGE_REGISTRY/otb-ubuntu-superbuild-base:18.04
  script:
    - ctest -VV -S CI/main_packages.cmake -DIMAGE_NAME:string=otb-ubuntu-superbuild-base
  dependencies:
    - ubuntu-superbuild-build

centos-package:
  extends: .superbuild-package
  image: $BUILD_IMAGE_REGISTRY/otb-centos-superbuild-base:6.6
  script:
    - ctest -VV -S CI/main_packages.cmake -DIMAGE_NAME:string=otb-centos-superbuild-base
  dependencies:
    - centos-superbuild-build

# TODO: CTT: Include osx-package here.
