variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

.retry_twice:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

natif-build:
  extends: .retry_twice
  stage: build
  image: registry.orfeo-toolbox.org/sdinot/otb:ubuntu-18.04-gcc
  script:
    - ctest -S CI/main_ci.cmake

shark-build:
  extends: .retry_twice
  stage: build
  image: registry.orfeo-toolbox.org/sdinot/otb:ubuntu18.04-shark3.1.4
  script:
    - ctest -VV -S CI/main_ci.cmake