variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

.retry_twice:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

build:ubuntu-18.04:release:
  extends: .retry_twice
  stage: build
  image: registry.orfeo-toolbox.org/sdinot/otb:ubuntu-18.04-gcc
  script:
    - ctest -S main_ci.cmake
  artifacts:
    expire_in: 1 week
    paths:
      - build/Testing/*/Test.xml
