variables:
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: "3"

stages:
  - build

.general:
  only: [merge_requests]
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

native-build:
  extends: .general
  stage: build
  image: registry.orfeo-toolbox.org/gbonnefille/otb-build-env/otb-ubuntu-native:18.04
  script:
    - ctest -VV -S CI/main_ci.cmake -DIMAGE_NAME:string=ubuntu-18.04-gcc

shark-build:
  extends: .general
  stage: build
  image: registry.orfeo-toolbox.org/gbonnefille/otb-build-env/otb-ubuntu-shark:18.04
  script:
    - ctest -VV -S CI/main_ci.cmake -DIMAGE_NAME:string=ubuntu-18.04-gcc-shark-3.1.4
